require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'


target 'InputDemoApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  
  pod 'react-native-payments', :path => '../node_modules/react-native-payments'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-camera-roll/camera-roll'

  target 'InputDemoAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  
  # use_flipper!({'Flipper' => '0.58.0'}) # should match the version of your Flipper client app
  post_install do |installer|
    react_native_post_install(installer) 
  end
end

target 'MessagesExtension' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
end


